services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file: .env # Load environment variables from the .env file
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: task-manager-db # The name of your database
      POSTGRES_USER: postgres # Database username
      POSTGRES_PASSWORD: admin # Database password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
