version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      # Set individual environment variables for connecting to PostgreSQL
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: task-manager-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: task-manager-db # The name of your database
      POSTGRES_USER: postgres # Database username
      POSTGRES_PASSWORD: admin # Database password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
